// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMJbzN4rAM8vKHHPEsVEELZAOwfYmK8m0',
    appId: '1:545984104990:web:0de6bbded87c3cebdcbc0f',
    messagingSenderId: '545984104990',
    projectId: 'testace2020',
    authDomain: 'testace2020.firebaseapp.com',
    databaseURL: 'https://testace2020-default-rtdb.firebaseio.com',
    storageBucket: 'testace2020.appspot.com',
    measurementId: 'G-B4PEVS29NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpB3keZOObWgXjvIeZLwNivubDDttTxlg',
    appId: '1:545984104990:android:5bd8456b942936aadcbc0f',
    messagingSenderId: '545984104990',
    projectId: 'testace2020',
    databaseURL: 'https://testace2020-default-rtdb.firebaseio.com',
    storageBucket: 'testace2020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYNXMnS4a6wNV-S4o21Zn2Fg341TetEw',
    appId: '1:545984104990:ios:0fd6aae96104679ddcbc0f',
    messagingSenderId: '545984104990',
    projectId: 'testace2020',
    databaseURL: 'https://testace2020-default-rtdb.firebaseio.com',
    storageBucket: 'testace2020.appspot.com',
    iosClientId: '545984104990-2jk28e4rlas8r5ggnlqp3nbef1a6ktm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ace',
  );
}
